dist: trusty
sudo: true
language: python
python:
  - '3.6'
services:
  - xvfb
install:
  - pip install -r requirements.txt
  - export PYTHONPATH=$TRAVIS_BUILD_DIR
  - export PYTHONDONTWRITEBYTECODE=1
script: xvfb-run --server-args="-screen 0 1024x768x24" pytest -v
env:
  global:
    - ANKI_ADDON_ID: 456732182

deploy:
  - provider: script
    script: python deploy.py
    on:
      branch: master

  - provider: releases
    api-key:
      secure: dRGQfrEcQJyhKjk7LNv4HHFvUPQWsHDuaAp1oqs0LuxjSz0Mb3LcbMJzEdqqNcnL1DN777Vm82Fwy5zxI23xPVgUdmwlkxualV/gC6mzIBlUHk5CHzV1Rx2uczWWyglRiGKHyOoL6JDIk7FULuPyKUT75uTC5GRS3K1q7u07lsXu8pr9P7+Esv0YuR59cQtMEZ93aiIXnRFoFMqZ5h2hHaifd6GYfn6ojOqJKXOTRbC8sCOx6ZGTB34ZJ9jNPD7fnQjpsh+WyErrW8f9TXwN2eDLUDFpgy54gPx15GzmmbTFZ+zX1YtpPQbtS0YAIAWJZl0WuZ9o2XNUgpVZfWJ7Gy/vLbFn7ZBQZs+vVpp8OiDAgwaq2GciQZhBs/noXe8whRT2v753j0YoaMLcx59viJHfRdMTgGnqeavS5lxzSM5g1oSenRfatDg2bs/FGX1UVpjeY6wOrTt46W6O79nP3YTZmWmRO25TEbPJ3SH8uDj3ofLOcnUngnEeCTfiLED8CIDEY0B/WUyb8KJ5EGrZQHhodGse/YCXNafkviiVNsoNqWgWhWtGhW/AuIeiGUw2KlwQppigyK/162tzYWy5+xvOLqQXPiFbZWMJSHDaxusvoIE5J8CK8tKzXNa3+QCoYnLyQSF2B/P9KepuBzn47VBL25NJAwoMedKprCt1SbY=
    file_glob: true
    file: Dict2Anki-*.zip
    skip_cleanup: false
    draft: true
    on:
      branch: master
